@api = http://localhost:3001/recibo


GET {{api}}
###

POST {{api}}
Content-Type: application/json

{
    "ESTADO": "Compra",
    "TITULAR": "Fernando",
    "PESO": "30",
    "FECHA_CREADO": "15/08/2021",
    "PRECIO": 3000,
    "PRECIO_U": 50,
    "CREADO": 1,
    "DIRECCION": "calle 123"
}

###
GET {{api}}/4

###
DELETE {{api}}/10020


###
GET {{api}}/count


###
PUT {{api}}/6
Content-Type: application/json

{
    "ESTADO": "Liquidado",
    "TITULAR": "Luis",
    "PESO": "30",
    "FECHA_CREADO": "15/08/2021",
    "PRECIO": 3000,
    "PRECIO_U": 50,
    "CREADO": 1,
    "DIRECCION": "calle 123"
}