@api = http://localhost:3001/recibo


GET {{api}}
###

POST {{api}}
Content-Type: application/json

{
    "ESTADO": "Compra",
    "TITULAR": "Fernando",
    "PESO": "30",   
    "PRECIO": 3000,
    "PRECIO_U": 50,
    "CREADO": 1,
    "DIRECCION": "calle 123",
     "FECHA_CREADO": "2021-09-25",
}

###
GET {{api}}/8

###
DELETE {{api}}/10020


###
GET {{api}}/count


###
PUT {{api}}/6
Content-Type: application/json

{
    "ESTADO": "Liquidado",
    "TITULAR": "Luis",
    "PESO": "30",    
    "PRECIO": 3000,
    "PRECIO_U": 50,
    "CREADO": 1,
    "DIRECCION": "calle 123",
    "FECHA_CREADO": "2021-09-25",
}