export const queries = {
  getAllRec:
    "select ESTADO,TITULAR,PESO,FECHA_CREADO,PRECIO,PRECIO_U,CREADO,DIRECCION from RECIBOS",
  createNewRec:
    "INSERT INTO RECIBOS (ESTADO,TITULAR,PESO,FECHA_CREADO,PRECIO,PRECIO_U,CREADO,DIRECCION) VALUES(@ESTADO,@TITULAR,@PESO,@FECHA_CREADO,@PRECIO,@PRECIO_U,@CREADO,@DIRECCION)",
  getIdRec:
    "SELECT ESTADO, TITULAR,PESO,FECHA_CREADO,PRECIO,PRECIO_U,CREADO,DIRECCION FROM RECIBOS WHERE CONSECUTIVOS =@CONSECUTIVO",
  deleteIdRec: "DELETE FROM RECIBOS WHERE CONSECUTIVOS= @CONSECUTIVOS",
  getTotalRec: "SELECT COUNT(*) FROM RECIBOS",
  upDateRec:
    "UPDATE RECIBOS SET ESTADO = @ESTADO, TITULAR=@TITULAR,PESO=@PESO,FECHA_CREADO=@FECHA_CREADO,PRECIO=@PRECIO,PRECIO_U=@PRECIO_U,CREADO=@CREADO,DIRECCION=@DIRECCION WHERE CONSECUTIVOS = @CONSECUTIVOS",
};
