export const queries = {
  getAllRec:
    "select CONSECUTIVOS,ESTADO,TITULAR,PESO,PRECIO,PRECIO_U,u.NOMBRE_USUARIO,DIRECCION,FECHA_CREADO from RECIBOS AS r INNER JOIN USUARIOS as u ON r.CREADO = u.ID_USUARIO;",
  createNewRec:
    "INSERT INTO RECIBOS (ESTADO,TITULAR,PESO,PRECIO,PRECIO_U,CREADO,DIRECCION,FECHA_CREADO) VALUES(@ESTADO,@TITULAR,@PESO,@FECHA_CREADO,@PRECIO,@PRECIO_U,@CREADO,@DIRECCION)",
  getIdRec:
    "SELECT CONSECUTIVOS,ESTADO, TITULAR,PESO,PRECIO,PRECIO_U,u.NOMBRE_USUARIO,DIRECCION,FECHA_CREADO, (SELECT DATEDIFF(day, FECHA_CREADO, GETDATE())) AS 'DIAS' FROM RECIBOS AS r INNER JOIN USUARIOS as u ON r.CREADO = u.ID_USUARIO WHERE r.CONSECUTIVOS=@CONSECUTIVO",
  deleteIdRec: "DELETE FROM RECIBOS WHERE CONSECUTIVOS= @CONSECUTIVOS",
  getTotalRec: "SELECT COUNT(*) FROM RECIBOS",
  upDateRec:
    "UPDATE RECIBOS SET ESTADO = @ESTADO, TITULAR=@TITULAR,PESO=@PESO,PRECIO=@PRECIO,PRECIO_U=@PRECIO_U,CREADO=@CREADO,DIRECCION=@DIRECCION,FECHA_CREADO=@FECHA_CREADO WHERE CONSECUTIVOS = @CONSECUTIVOS",
};
